r-multiverse/r-multiverse.github.io

- contributors.qmd
- users.qmd
Simplifies instructions + puts the rare case in a collapsed callout.
> simplifies contribution instructions

- about.qmd
@wlandau let me know if this is adequate for what you had in mind. thx.
> clarify description wording

- users.qmd
@wlandau would like your opinion on this version.
I think the advantages are:
- makes users page less cluttered
- use cases better organised under one heading
- collapsed callouts create interactivity on the page should boost engagement (also looks too busy if not collapsed)
> streamline users page

- contributors.qmd
@shikokuchuo, this PR embeds a 2-minute video showing how to use the GitHub UI to contribute packages.
> Embed tutorial video

- _quarto.yml
- styles.css
@wlandau are you ok to put these in the footer? Makes the site a bit more minimalist.
> Put review policy and CoC in footer

- users.qmd
Addresses https://github.com/r-multiverse/help/issues/45. I think we can be general, without making any specific claims about the inner workings of `install.packages()`.
> Update package installation guidance

- _quarto.yml
- team.qmd
There are sections for team members and the roles of each member.
> Add a team.qmd page

- _quarto.yml
- security.qmd
Fixes https://github.com/r-multiverse/help/issues/56
> Add security policy

- contributors.qmd
Completes https://github.com/r-multiverse/r-multiverse.github.io/pull/19#issuecomment-2313320262.
> Updates contribution example to use Arrow

- contributors.qmd
- review.md
Fixes https://github.com/r-multiverse/help/issues/85.
> Fix code of conduct links

- team.qmd
Please let me know if you'd like any amendments. Thanks.
> Adds Maëlle to team page

- about.qmd
- team.qmd
Please let me know if you'd like any amendments. Thanks.
> Add Jeroen to team page

- governance.md
As per https://github.com/r-multiverse/help/issues/91.
> Removes affilliations from RMC members in governance doc

- R/utils.R
- overview.qmd
- production.qmd
* Report base R version at the time of the snapshot.
* Explain snapshot compatibility concerns.
* Format code chunks.
> clarifications and formatting

- governance.md
- team.md
c.f. https://github.com/r-multiverse/help/issues/114. Scheduled to take effect on Jan 9 if there there is enough agreement.
> Governance: minor improvements to spelling, grammar and wording

- index.md
As discussed, there is still confusion about what R-multiverse is. Perhaps *general-purpose R package repository system* is too vague.
Here a proposal to update our one-line pitch to make it more explicit what multiverse is, and how it relates to r-universe, even if folks do not read the entire documentation.
@maelle @wlandau @shikokuchuo how does this sound to you?
> Update frontpage pitch

- .github/workflows/render.yaml
- R/utils.R
follow-up to https://github.com/r-multiverse/help/issues/116 and https://github.com/r-multiverse/production/pull/4
> use r_version.txt and date.txt from https://github.com/r-multiverse/production

- _quarto.yml
- index.md
c.f. https://github.com/r-multiverse/help/issues/134#issuecomment-2672696501
Planning to merge on Feb 28.
> Describe R-multiverse as a "dual repository"

- .github/workflows/render.yaml
- R/utils.R
- overview.qmd
- production.qmd
as discussed in https://github.com/r-multiverse/help/issues/135
> Change snapshot schedule

- production.qmd
and group them into intuitive categories
> update descriptions of enforced checks

- contributors.md
- production.qmd
This PR describes the Staging process more accurately, especially after https://github.com/r-multiverse/multiverse.internals/pull/60. (also c.f. https://github.com/r-multiverse/help/issues/141#issuecomment-2706605447).
Unless there are objections, I will merge this on Wed. March 12.
> Describe the Staging process more accurately

- team.md
Hi @wlandau pls merge this if you're fine with it. Thanks!
> Updates Team Page

- production.qmd
This PR mentions the available binaries and their year-long retention period.
> mention binaries
